version: '3'

services:
  nginx-proxy:
    restart: always
    image: nginx:1.15.10 #stable version on 11/04/2019
    container_name: nginx_container
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx_conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx_conf/conf.d:/etc/nginx/conf.d
      - ./static-html-directory:/usr/share/nginx/html
      - /var/log/nginx/log:/var/log/nginx_volume/log
      - /etc/letsencrypt:/etc/letsencrypt
      #jenkins
   #   - ../JenkinsDC/jenkins_home:/var/jenkins_home

    networks:
      - default
      - elastestjenkins
      - nexusdc
      - userregistry

networks:
   elastestjenkins:
     external:
       name: elastestjenkinsdc_default

   nexusdc:
     external:
       name: nexusdc_default

   userregistry:
     external: 
       name: private-user-registry_default

#volumes:
#   jenkins_home:
#     external:
#       name: jenkinsdc_jenkins_home
#  letsencrypt-nginx-proxy-companion:
#    restart: always
#    image: jrcs/letsencrypt-nginx-proxy-companion
#    container_name: proxy_letsencrypt-nginx-proxy-companion
#    volumes_from:
#      - nginx-proxy
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock:ro
#      - /data/letsencrypt-nginx-proxy-companion/certs/:/etc/nginx/certs:rw


